name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/manelfideles/t3-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        run: make lint
      - name: Format
        run: make lint_fix
      - name: Type check
        run: make typecheck
      - name: Test
        run: make test
